apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        - name: init-order-db
          image: louisscrf/order-service:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              if [ -d /mnt/prisma/dev.db ]; then
                rm -rf /mnt/prisma/dev.db
              fi
              if [ ! -f /mnt/prisma/dev.db ]; then
                mkdir -p /mnt/prisma
                cp -r /app/prisma/. /mnt/prisma/
              fi
          volumeMounts:
            - name: order-storage
              mountPath: /mnt/prisma

      containers:
        - name: order-service
          image: louisscrf/order-service:latest
          ports:
            - containerPort: 4000

          env:
            - name: DATABASE_URL
              value: "file:./dev.db"
            - name: JWT_SECRET
              value: "change-me"
            - name: PORT
              value: "4000"

          volumeMounts:
            - name: order-storage
              mountPath: /app/prisma

          # Vérifie si l’app répond
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10

          # Vérifie si l’app est prête à recevoir du trafic
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 2
            periodSeconds: 5

      volumes:
        - name: order-storage
          persistentVolumeClaim:
            claimName: order-pvc
